### ISSUE TITLE
Jak zabít čas načítání

### ISSUE THREAD

**Issue by hernikplays** [KDUI/kdui#2]
https://github.com/KDUI/kdui/blob/2519980c6f4baa791e550e8f672542cd63fdfa64/kdui.ver1.uncompiled.css#L42

```
Always import your fonts from HTML, not CSS.

By moving our font request to the <head> of our HTML instead, we can make our load faster because we've reduced the number of links in the chain for getting our font files
```
👉 [Making Google Fonts Faster in 2022](https://sia.codes/posts/making-google-fonts-faster/#should-i-use-%3Clink%3E-or-%40import%3F)

**Comment by Klema4** [comment]
Hello, @hernikplays.
Thanks for your contribution! We appreciate your help.
As of now, the font import is built in the CSS because of the fonts you can customize in the root.

Your idea seems better and faster IMHO. We'll take a look at your idea and make possible changes later in the dev builds.
Thanks for your patience!

Kind regards,
Kléma, founder of KDUI

**Comment by Klema4** [comment]
Merged into the dev branch. People can still choose if they want fonts imported in CSS or not. 

Closing this issue.
